// Reading from YouTube (YouTube as transfer source). Mirrors
// spotifySource.js's fetchAllTracks for the reverse direction
// (YouTube -> Spotify). Unlike Spotify, YouTube gives no structured
// song/artist/album fields for a video — just a title, an uploading
// channel, and (often) a distributor-generated description — so they have
// to be parsed with heuristics (see parseVideoMetadata below).

import { auth, songs, PLACEHOLDER_ALBUM_ART } from './state.js';
import { YouTubeAuthError, YouTubeQuotaError, throwIfApiError, fetchAllYouTubeItems } from './youtubeClient.js';
import { showToast } from './toast.js';

// ─── Title/Description Parsing ─────────────────────────────────────────────────

// Strips common upload-title clutter like "(Official Video)", "[Lyrics]",
// "(Audio)" etc. so the parsed song name is closer to the real title.
const TITLE_JUNK_RE =
  /[([][^()[\]]*\b(official|audio|video|lyrics?|visualizer|hd|4k|remaster(?:ed)?|explicit|clean)\b[^()[\]]*[)\]]/gi;

function cleanVideoTitle(title) {
  return title.replace(TITLE_JUNK_RE, "").replace(/\s{2,}/g, " ").trim();
}

// YouTube's auto-generated channels for a music artist are always named
// "<Artist> - Topic" — a reliable signal that the channel name IS the artist.
const TOPIC_CHANNEL_RE = /\s-\sTopic$/;

// Distributors that deliver music to YouTube (CD Baby, DistroKid, Believe,
// etc.) use a standard auto-generated description template — the same
// underlying metadata YouTube Music's own UI displays, just not exposed as
// structured API fields:
//   Provided to YouTube by <distributor>
//
//   <Song Title> · <Artist 1> · <Artist 2> · ...
//
//   <Album Name>
//
//   ℗ <year> <label>
//
//   Released on: <date>
// The song/artist line lists every collaborating artist separated by " · "
// (mirroring the original multi-artist credits, e.g. from Spotify, that the
// distributor submitted) — not just a single song/artist pair. Parses that
// structure out of the description text when present.
function parseAutoGeneratedDescription(description) {
  if (!description) return null;

  const lines = description.split("\n").map((line) => line.trim()).filter(Boolean);
  const songArtistIndex = lines.findIndex((line) => line.includes(" · "));
  if (songArtistIndex === -1) return null;

  const [song, ...artists] = lines[songArtistIndex].split(" · ").map((s) => s.trim());
  const albumLine = lines[songArtistIndex + 1];
  const album = albumLine && !/^℗|^released on:/i.test(albumLine) ? albumLine : null;

  return { song, artists, album };
}

// Guesses a song/artists/album from a video's own title, description, and
// uploading channel (all three come from the video resource itself, via
// videos.list — never from the playlist item, whose "channelTitle" means
// "who added this to the playlist", not "who uploaded the video").
// Preference order: the distributor-provided description (most reliable,
// and the only source that can reveal multiple collaborating artists) >
// the "Artist - Topic" channel convention > splitting the title on
// "Artist - Song"-style separators > the channel name as a last resort.
function parseVideoMetadata({ title, description, channelTitle }) {
  const cleaned         = cleanVideoTitle(title);
  const fromDescription = parseAutoGeneratedDescription(description);
  const topicMatch      = channelTitle && channelTitle.match(TOPIC_CHANNEL_RE);
  const topicArtist     = topicMatch ? channelTitle.replace(TOPIC_CHANNEL_RE, "").trim() : null;

  if (fromDescription && fromDescription.artists.length > 0) {
    return {
      name:    fromDescription.song || cleaned,
      artists: fromDescription.artists,
      album:   fromDescription.album || "Not Found",
    };
  }

  if (topicArtist) {
    return { name: cleaned, artists: [topicArtist], album: "Not Found" };
  }

  const parts = cleaned.split(/\s[-–|]\s/);
  if (parts.length >= 2) {
    return { name: parts.slice(1).join(" - ").trim(), artists: [parts[0].trim()], album: "Not Found" };
  }

  return { name: cleaned, artists: channelTitle ? [channelTitle] : [], album: "Not Found" };
}

// ─── Music Playlist Detection ───────────────────────────────────────────────────

const MUSIC_CATEGORY_ID = "10";
const MUSIC_LIKE_RATIO  = 0.5;

// Looks up every video's own snippet — title, description, uploading
// channel, and upload category — in batches of up to 50 ids per call (1
// quota unit per call regardless of batch size). This single pass covers
// three needs at once (artist/album parsing, music-playlist detection, and
// thumbnails), rather than spending a separate call per concern.
async function fetchVideoDetails(videoIds) {
  const details = new Map();

  for (let i = 0; i < videoIds.length; i += 50) {
    const batch = videoIds.slice(i, i + 50);
    const res   = await fetch(
      `https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id=${batch.join(",")}`,
      { headers: { Accept: "application/json", Authorization: `Bearer ${auth.youtubeAccessToken}` } }
    );
    const data = await res.json();
    throwIfApiError(data, res);

    (data.items || []).forEach((v) => {
      details.set(v.id, {
        title:        v.snippet.title,
        description:  v.snippet.description,
        channelTitle: v.snippet.channelTitle,
        categoryId:   v.snippet.categoryId,
        thumbnailUrl: v.snippet.thumbnails?.default?.url,
      });
    });
  }

  return details;
}

// Decides whether a playlist is a music playlist (e.g. "My Favorite Songs")
// as opposed to an unrelated one (e.g. "Cooking Videos"), using the video
// details already fetched above — an "Artist - Topic" channel or an
// official Music category both count as a music-like signal.
function isMusicPlaylist(videoIds, details) {
  if (videoIds.length === 0) return false;

  const musicLikeCount = videoIds.filter((id) => {
    const video = details.get(id);
    return !!video && (TOPIC_CHANNEL_RE.test(video.channelTitle || "") || video.categoryId === MUSIC_CATEGORY_ID);
  }).length;

  return musicLikeCount / videoIds.length >= MUSIC_LIKE_RATIO;
}

// ─── Source Reading ─────────────────────────────────────────────────────────────

// Loads the user's music playlists (auto-detected via isMusicPlaylist — see
// above) and their videos into the songs state object. Non-music playlists
// (e.g. "Cooking Videos") are skipped entirely so they never show up for
// transfer. Returns false if the API call fails (e.g. expired token) —
// mirrors fetchAllTracks's boolean contract so initiate() can treat both
// directions identically, regardless of which point in the process failed.
export async function fetchAllYouTubePlaylists() {
  try {
    const playlists = await fetchAllYouTubeItems(
      "https://youtube.googleapis.com/youtube/v3/playlists?part=snippet&mine=true&maxResults=50"
    );

    for (const playlist of playlists) {
      const playlistItems = await fetchAllYouTubeItems(
        `https://youtube.googleapis.com/youtube/v3/playlistItems?part=contentDetails&maxResults=50&playlistId=${playlist.id}`
      );
      const videoIds = playlistItems.map((item) => item.contentDetails.videoId);
      const details  = await fetchVideoDetails(videoIds);

      if (!isMusicPlaylist(videoIds, details)) continue;

      for (const videoId of videoIds) {
        // Deleted/private videos simply aren't returned by videos.list at all.
        const video = details.get(videoId);
        if (!video) continue;

        const { name, artists, album } = parseVideoMetadata(video);
        if (!name) continue;

        songs.names.push(name);
        songs.trackIds.push(videoId);
        songs.artists.push(
          artists.length > 0 ? artists.map((a) => ({ name: a })) : [{ name: "Unknown Artist" }]
        );
        songs.playlists.push(playlist.snippet.title || "Not Found");
        songs.albums.push(album);
        songs.albumArts.push(video.thumbnailUrl || PLACEHOLDER_ALBUM_ART);
      }
    }

    return true;
  } catch (err) {
    if (err instanceof YouTubeAuthError) {
      showToast("Failed to load YouTube playlists. Your session may have expired — please reconnect.");
      return false;
    }
    if (err instanceof YouTubeQuotaError) {
      showToast(
        "The daily YouTube API quota was reached while loading your playlists. YouTube resets it " +
        "around midnight Pacific Time — please come back after that."
      );
      return false;
    }
    throw err;
  }
}
